[general]
import = [
#  "~/.config/alacritty/themes/themes/tokyo_night.toml"
   "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

#option_as_alt = "Both"

[font]
size = 18.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"



